import javax.swing.*;
import java.util.List;
import java.awt.*;
import java.awt.event.*;
import com.mongodb.*;
import com.mongodb.client.*;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author adit
 * @revised Klimentina
 */
public class MenuDefTyp extends JFrame 
{
    /**
     * Creates new form MenuDefTyp
     */
    public MenuDefTyp() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
    	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        BackToMain = new JButton("Back");
        BackToMain.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent evt) 
            {
                BackToMainActionPerformed(evt);
            }
        });
        getContentPane().add(BackToMain);
        BackToMain.setBounds(0, 0, 72, 29);

        TypTextArea = new JTextArea();
        TypTextArea.setColumns(20);
        TypTextArea.setRows(5);
        
        jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(TypTextArea);
        jScrollPane1.setBounds(70, 30, 500, 180);
        getContentPane().add(jScrollPane1);
        

        setSize(new Dimension(627, 267));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMainActionPerformed(ActionEvent evt) 
    {//GEN-FIRST:event_BackToMainActionPerformed
        this.dispose();
    }//GEN-LAST:event_BackToMainActionPerformed

	public void getTypes()
	{
		MongoClient mongoClient = new MongoClient("localhost", 27017);
		MongoDatabase db = mongoClient.getDatabase("database");
		MongoCollection<Document> elexirCollection = db.getCollection("test");

		FindIterable<Document> results = elexirCollection.find(new BasicDBObject("Objects", new BasicDBObject("$gt", ".0001")));
		//FindIterable<Document> iter = elexirCollection.find(new BasicDBObject("derivProb", 2));
		
		for (Document doc : results) 
		{
			// do something with each result
			List<String> conv  =  (List<String>)doc.get("Types");
			String [] convArr = new String[conv.size()];
			convArr = conv.toArray(convArr);
			for(String s: convArr)
				TypTextArea.append(s + "\n");
		}
		mongoClient.close();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BackToMain;
    private static JTextArea TypTextArea;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
